apiVersion: v1
kind: Service
metadata:
  name: backend
  # apps_name: thunderstorm
spec:
  selector:
    app: backend
    apps_name: thunderstorm
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
    # - name: http-alt
    #   protocol: TCP
    #   port: 8080
    #   targetPort: 8080
