apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    apps_name: thunderstorm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      apps_name: thunderstorm
  template:
    metadata:
      labels:
        app: backend
        apps_name: thunderstorm
    spec:
      containers:
        - name: backend
          image: devopseasylearning/thunderstrom-backend:002
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB
              value: endgame
            - name: DB_HOST
              value: db
            - name: DB_PASS
              value: example
            - name: DB_USER
              value: john

